    ### Spring properties
    # Service registers under this name
    spring:
      application:
        name: customer-service
      mvc:
        view:
          prefix: /WEB-INF/view/
          suffix: .jsp
        static-path-pattern: /resources/**

    # Discovery Server Access
    eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8070/eureka/

    # HTTP Server (Tomcat) Port
    server: 
      port: 8072

    

    # Disable Spring Boot's "Whitelabel" default error page, so we can use our own
    error:
      whitelabel:
        enabled: false